### ISSUE TITLE
Panic during the runtime

### ISSUE THREAD

**Issue by kayrus** [jvermillard/nativedtls#3]
Using master openssl branch, get this issue during the `nativedtls.NewDTLSClient(ctx, conn)`:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f32e00008d0 pc=0x7f32e00008d0]

runtime stack:
runtime.throw(0xc28be1, 0x2a)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall]:
runtime.cgocall(0x8b4160, 0xc00020b878, 0xc000138300)
        /usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00020b848 sp=0xc00020b810 pc=0x46cb5b
github.com/jvermillard/nativedtls._Cfunc_SSL_connect(0x7f32e0000c90, 0xc000000000)
        _cgo_gotypes.go:381 +0x45 fp=0xc00020b878 sp=0xc00020b848 pc=0x84a0e5
```

I also tried the submodule commit hash, but openssl doesn't build

**Comment by jvermillard** [comment]
I should deprectae this repo, there is much more complete and active alternatives: https://github.com/pion/dtls

**Comment by kayrus** [comment]
Unfortunately it doesn't support DTLSv1.0. I have a strict dependency for exact this version.

**Comment by jvermillard** [comment]
if you feel like maintaining it, the project is your :)
